// Autenticacion
export const AUTH_USUARIO = "AUTH_USUARIO";
export const CERRAR_SESION = "CERRAR_SESION";

// Peliculas
export const OBTENER_PELICULAS = "OBTENER_PELICULAS";
export const OBTENER_PELICULA = "OBTENER_PELICULA";
export const AGREGAR_FAVORITO = "AGREGAR_FAVORITO";
export const OBTENER_FAVORITOS = "OBTENER_FAVORITOS";
export const QUITAR_FAVORITO = "QUITAR_FAVORITO";
